/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Center, Decal, useGLTF, useTexture } from "@react-three/drei";
import { useEffect, useRef, useMemo, useState } from "react";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import {
  CANVAS_CONFIG,
  TSHIRT_TYPES,
  TSHIRT_COLOR_CODES,
  PRINT_AREA,
} from "../constants/designConstants";


export function TshirtModel({
  tshirtColor,
  selectedType,
  selectedView,
  designTexture,
  designTextureBack,
  onViewChange,
}) {
  const modelPath = TSHIRT_TYPES[selectedType]?.modelPath || "/3Dmodels/02.glb";
  const { nodes, materials, scene } = useGLTF(modelPath);

  const frontMeshName = TSHIRT_TYPES[selectedType]?.frontMeshName || "front";
  const backMeshName = TSHIRT_TYPES[selectedType]?.backMeshName || "back";
  const modelScale = TSHIRT_TYPES[selectedType]?.modelScale || 4.0;
  const modelRotation = TSHIRT_TYPES[selectedType]?.modelRotation || [Math.PI / 2, 0, 0];
  const modelPosition = TSHIRT_TYPES[selectedType]?.modelPosition || [0, 0.4, 0];
  const decalConfig = TSHIRT_TYPES[selectedType]?.decalConfig || {
    front: { position: [0, 0.05, -0.27], rotation: [Math.PI / 2, Math.PI, Math.PI] },
    back: { position: [0, -0.22, -0.27], rotation: [Math.PI / 2 - 0.2, 0, Math.PI] }
  };
  const logoConfig = TSHIRT_TYPES[selectedType]?.logoConfig || null;

  const isOversized = selectedType === "oversized";

  // Pick logo version based on shirt brightness (white logo on dark shirts, black logo on light shirts)
  const isDarkShirt = useMemo(() => {
    const color = new THREE.Color(tshirtColor);
    // luminance formula: 0.2126R + 0.7152G + 0.0722B
    const luminance = 0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b;
    return luminance < 0.4;
  }, [tshirtColor]);

  // Use a cache-busting timestamp so Three.js doesn't reuse an older/mirrored SVG
  const logoUrl = isDarkShirt ? "/logo-white.svg" : "/logo-black.svg";

  // Collect actual meshes from the scene graph
  const allMeshes = useMemo(() => {
    const knownCrewNeckMeshes = new Set(["T-Shirt", "T-Shirt_1", "T-Shirt_2", "T-Shirt_3", "T-Shirt_4", "T-Shirt_5", "front", "back"]);
    const meshes = [];
    if (scene) {
      scene.traverse((child) => {
        if (child.isMesh && child.geometry) {
          const shouldInclude = isOversized || knownCrewNeckMeshes.has(child.name);
          if (shouldInclude) {
            meshes.push(child);
          }
        }
      });
    }
    return meshes;
  }, [scene, isOversized]);

  // =====================================================
  //  BOUNDING BOX — compute for ALL model types
  // =====================================================
  const meshBBoxData = useMemo(() => {
    const data = {};
    allMeshes.forEach((mesh) => {
      if (mesh.name === frontMeshName || mesh.name === backMeshName) {
        mesh.geometry.computeBoundingBox();
        const box = mesh.geometry.boundingBox;
        if (box) {
          const center = new THREE.Vector3();
          const size = new THREE.Vector3();
          box.getCenter(center);
          box.getSize(size);
          data[mesh.name] = { center, size };
        }
      }
    });
    return data;
  }, [allMeshes, frontMeshName, backMeshName]);

  // =====================================================
  //  TEXTURES
  // =====================================================

  // --- Crew-neck textures via useTexture ---
  const crewTexture = useTexture(
    !isOversized && designTexture ? designTexture : "/3Dmodels/textures/design-fallback.png"
  );
  const crewTextureBack = useTexture(
    !isOversized && designTextureBack ? designTextureBack : "/3Dmodels/textures/design-fallback.png"
  );

  // --- Oversized textures via manual TextureLoader ---
  const [oversizedFrontTex, setOversizedFrontTex] = useState(null);
  const [oversizedBackTex, setOversizedBackTex] = useState(null);
  const [logoTexture, setLogoTexture] = useState(null);
  const [crewLogoTexture, setCrewLogoTexture] = useState(null);

  useEffect(() => {
    if (!isOversized) return;
    if (!designTexture) { setOversizedFrontTex(null); return; }
    const loader = new THREE.TextureLoader();
    loader.load(designTexture, (tex) => {
      tex.flipY = true;
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.minFilter = THREE.LinearFilter;
      tex.magFilter = THREE.LinearFilter;
      tex.generateMipmaps = true;
      tex.anisotropy = 16;
      tex.needsUpdate = true;
      setOversizedFrontTex(tex);
    });
  }, [designTexture, isOversized]);

  useEffect(() => {
    if (!isOversized) return;
    if (!designTextureBack) { setOversizedBackTex(null); return; }
    const loader = new THREE.TextureLoader();
    loader.load(designTextureBack, (tex) => {
      tex.flipY = true;
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.minFilter = THREE.LinearFilter;
      tex.magFilter = THREE.LinearFilter;
      tex.generateMipmaps = true;
      tex.anisotropy = 16;
      tex.needsUpdate = true;
      setOversizedBackTex(tex);
    });
  }, [designTextureBack, isOversized]);

  // Load logo texture for oversized model
  useEffect(() => {
    if (!isOversized) return;
    const loader = new THREE.TextureLoader();
    loader.load(logoUrl, (tex) => {
      tex.flipY = false;  // Original UV mapping requires false
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.minFilter = THREE.LinearFilter;
      tex.magFilter = THREE.LinearFilter;
      tex.generateMipmaps = true;
      tex.anisotropy = 16;

      // Original oversized mapping values
      tex.repeat.set(1.2, 4.8);
      tex.offset.set(-0.1, -0.6);

      tex.needsUpdate = true;
      setLogoTexture(tex);
    });
  }, [isOversized, logoUrl]);

  // Load logo texture for crew-neck model
  useEffect(() => {
    if (isOversized) return;
    const loader = new THREE.TextureLoader();
    loader.load(logoUrl, (tex) => {
      tex.flipY = true;
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.minFilter = THREE.LinearFilter;
      tex.magFilter = THREE.LinearFilter;
      tex.generateMipmaps = true;
      tex.anisotropy = 16;
      tex.needsUpdate = true;
      setCrewLogoTexture(tex);
    });
  }, [isOversized, logoUrl]);

  // Pick the right texture based on model type
  const activeFrontTex = isOversized ? oversizedFrontTex : crewTexture;
  const activeBackTex = isOversized ? oversizedBackTex : crewTextureBack;

  const groupRef = useRef();

  // =====================================================
  //  DECAL SCALE
  // =====================================================
  const computeDecalScale = (meshName, customTexture, side) => {
    const bbox = meshBBoxData[meshName];
    if (!bbox) return PRINT_AREA.decalScale;

    if (isOversized) {
      const defaultScale = PRINT_AREA.decalScale;
      const multiplier = side === "front" ? 45.0 : 40.0;
      if (!customTexture || !customTexture.image || customTexture.image.width === 0) {
        return [defaultScale[0] * multiplier, defaultScale[1] * multiplier, 15.0];
      }
      const { width, height } = customTexture.image;
      const aspectRatio = width / height;
      const [maxW, maxH] = defaultScale;
      let finalW, finalH;
      if (aspectRatio > maxW / maxH) { finalW = maxW; finalH = maxW / aspectRatio; }
      else { finalH = maxH; finalW = maxH * aspectRatio; }
      return [finalW * multiplier, finalH * multiplier, 15.0];
    }

    // Crew-neck: use mesh bbox dimensions directly
    const meshW = bbox.size.x;
    const meshH = bbox.size.y;
    const depth = bbox.size.z + 0.5;

    if (!customTexture || !customTexture.image || customTexture.image.width === 0) {
      return [meshW, meshH, depth];
    }

    const { width, height } = customTexture.image;
    const imgAspect = width / height;
    const meshAspect = meshW / meshH;

    let finalW, finalH;
    if (imgAspect > meshAspect) {
      finalW = meshW;
      finalH = meshW / imgAspect;
    } else {
      finalH = meshH;
      finalW = meshH * imgAspect;
    }

    return [finalW, finalH, depth];
  };

  const frontDecalScale = computeDecalScale(frontMeshName, activeFrontTex, "front");
  const backDecalScale = computeDecalScale(backMeshName, activeBackTex, "back");


  // =====================================================
  //  MATERIALS
  // =====================================================
  const tshirtMaterial = useMemo(() => {
    const material = new THREE.MeshStandardMaterial({
      color: tshirtColor,
      roughness: 0.6,
      metalness: 0,
      transparent: false,
      opacity: 1.0,
      side: THREE.DoubleSide,
      depthWrite: true,
      depthTest: true,
    });
    return material;
  }, [tshirtColor]);

  // Crew-neck: update original materials with color
  const crewMaterials = useMemo(() => {
    if (isOversized) return new Map();
    const map = new Map();
    allMeshes.forEach((mesh) => {
      const mat = new THREE.MeshStandardMaterial({
        color: tshirtColor,
        roughness: 0.6,
        metalness: 0,
        side: THREE.DoubleSide,
        depthWrite: true,
        depthTest: true,
      });
      map.set(mesh.name, mat);
    });
    return map;
  }, [allMeshes, tshirtColor, isOversized]);

  // Oversized: cloned materials per mesh
  const clonedMaterials = useMemo(() => {
    if (!isOversized) return new Map();
    const map = new Map();
    allMeshes.forEach((mesh) => {
      const cloned = mesh.material.clone();
      cloned.map = null;
      cloned.normalMap = null;
      cloned.roughnessMap = null;

      if (mesh.name === frontMeshName && logoTexture) {
        cloned.map = logoTexture;
        cloned.emissive = new THREE.Color(isDarkShirt ? 0xffffff : 0x000000);
        cloned.emissiveMap = logoTexture;
        cloned.emissiveIntensity = 1.0;
        cloned.transparent = true;
        cloned.alphaTest = 0.5;
      } else {
        cloned.transparent = false;
        cloned.emissive = new THREE.Color(0x000000);
        cloned.emissiveMap = null;
      }

      const finalColor = new THREE.Color(tshirtColor);
      if (finalColor.r > 0.92 && finalColor.g > 0.92 && finalColor.b > 0.92) {
        finalColor.multiplyScalar(0.92);
      }
      cloned.color.set(finalColor);
      cloned.opacity = 1.0;
      cloned.side = THREE.DoubleSide;
      cloned.roughness = 0.85;
      cloned.metalness = 0;
      cloned.depthWrite = true;
      cloned.depthTest = true;
      cloned.needsUpdate = true;
      map.set(mesh.name, cloned);
    });
    return map;
  }, [allMeshes, tshirtColor, isOversized, frontMeshName, logoTexture, isDarkShirt]);

  // Smooth rotation — only interpolate when needed
  useFrame(() => {
    if (!groupRef.current) return;
    const targetRotation = selectedView === "back" ? Math.PI : 0;
    const diff = targetRotation - groupRef.current.rotation.y;
    if (Math.abs(diff) < 0.001) {
      // Snap to exact target and stop
      groupRef.current.rotation.y = targetRotation;
      return;
    }
    groupRef.current.rotation.y += diff * 0.1;
  });

  const handleClick = (view) => { onViewChange(view); };
  const isFrontMesh = (meshName) => meshName === frontMeshName || meshName.startsWith(frontMeshName);
  const isBackMesh = (meshName) => meshName === backMeshName || meshName.startsWith(backMeshName);

  // Get decal position: dynamically computed from mesh bounding box
  const getDecalPos = (meshName, side) => {
    const bbox = meshBBoxData[meshName];
    if (!bbox) return decalConfig[side].position;

    if (isOversized) {
      const yOffset = bbox.size.y / 2 + 0.5;
      const yPos = side === "front"
        ? bbox.center.y + yOffset
        : bbox.center.y - yOffset;
      return [bbox.center.x, yPos, bbox.center.z];
    }

    return [bbox.center.x, bbox.center.y, bbox.center.z];
  };

  return (
    <Center position={modelPosition}>
      <group ref={groupRef} dispose={null}>
        <group rotation={modelRotation} scale={modelScale}>
          {allMeshes.map((meshNode, index) => {
            const key = meshNode.name || `mesh-${index}`;
            const front = isFrontMesh(meshNode.name);
            const back = isBackMesh(meshNode.name);

            // Material: per-mesh for both model types
            let meshMaterial;
            if (isOversized) {
              meshMaterial = clonedMaterials.get(meshNode.name) || tshirtMaterial;
            } else {
              meshMaterial = crewMaterials.get(meshNode.name) || tshirtMaterial;
            }

            // Decal positions
            const frontPos = front ? getDecalPos(meshNode.name, "front") : null;
            const backPos = back ? getDecalPos(meshNode.name, "back") : null;

            // Has texture?
            const hasFront = isOversized ? !!oversizedFrontTex : !!designTexture;
            const hasBack = isOversized ? !!oversizedBackTex : !!designTextureBack;

            return (
              <mesh
                key={key}
                castShadow
                receiveShadow
                geometry={meshNode.geometry}
                material={meshMaterial}
                position={[0, 0, 0]}
                onClick={() => handleClick(front ? "front" : back ? "back" : selectedView)}
              >
                {/* LOGO DECAL — crew-neck only */}
                {front && frontPos && !isOversized && crewLogoTexture && (
                  <Decal
                    position={frontPos}
                    rotation={decalConfig.front.rotation}
                    scale={(() => { const s = logoConfig?.scale ?? [0.25, 0.08, 0.1]; return [s[0], s[1], s[2]]; })()}
                  >
                    <meshStandardMaterial
                      map={crewLogoTexture}
                      map-anisotropy={16}
                      toneMapped={false}
                      transparent
                      alphaTest={0.05}
                      side={THREE.FrontSide}
                      depthTest
                      depthWrite={false}
                      polygonOffset
                      polygonOffsetFactor={-20}
                      polygonOffsetUnits={-20}
                      roughness={0.5}
                      metalness={0}
                    />
                  </Decal>
                )}

                {/* FRONT DESIGN DECAL */}
                {front && hasFront && frontPos && (
                  <Decal
                    position={frontPos}
                    rotation={decalConfig.front.rotation}
                    scale={frontDecalScale}
                  >
                    <meshStandardMaterial
                      map={activeFrontTex}
                      map-anisotropy={16}
                      toneMapped={false}
                      transparent
                      side={THREE.FrontSide}
                      depthTest
                      depthWrite={false}
                      polygonOffset
                      polygonOffsetFactor={-10}
                      polygonOffsetUnits={-10}
                      roughness={0.5}
                      metalness={0}
                    />
                  </Decal>
                )}

                {/* BACK DESIGN DECAL */}
                {back && hasBack && backPos && (
                  <Decal
                    position={backPos}
                    rotation={decalConfig.back.rotation}
                    scale={[-backDecalScale[0], backDecalScale[1], backDecalScale[2]]}
                  >
                    <meshStandardMaterial
                      map={activeBackTex}
                      map-anisotropy={16}
                      toneMapped={false}
                      transparent
                      side={THREE.FrontSide}
                      depthTest
                      depthWrite={false}
                      polygonOffset
                      polygonOffsetFactor={-10}
                      polygonOffsetUnits={-10}
                      roughness={0.5}
                      metalness={0}
                    />
                  </Decal>
                )}
              </mesh>
            );
          })}
        </group>
      </group>
    </Center>
  );
}

useGLTF.preload("/3Dmodels/02.glb");
useGLTF.preload("/3Dmodels/oversized.glb");

